### ISSUE TITLE
Message number indicators do not update correctly

### ISSUE THREAD

**Issue by Felizolinha** [MegaScratchUserscript/Mega-Scratch-Userscript#25]
After reading your messages, the favicon does not return to normal, the same happens to the tab title.

**Comment by MegaApuTurkUltra** [comment]
Yep, I've noticed that. Not sure what causes it (the script is supposed to
check for changes every few seconds)

**Comment by MegaApuTurkUltra** [comment]
NVM, I was going to go open the code but I figured out exactly what it is
(I can't believe I still remember the code after like a month!)

There's something in there that looks like

if(number_of_messages > 0) {
    // update stuff
}

An else block needs to be added to revert the title/favicon if there are no
messages

**Comment by PullJosh** [comment]
Ohhhh... my bad. :3

**Comment by Felizolinha** [comment]
I'm almost sure the problem is the line [#L52](https://github.com/MegaScratchUserscript/Mega-Scratch-Userscript/blob/master/parts/titlemessages.part.js#L52).
I believe using this check would fix it: ``$('.notificationsCount').css('top').charAt(0) === "-"``

**Comment by MegaApuTurkUltra** [comment]
Oops I was wrong...welp

**Comment by Felizolinha** [comment]
Nvm, I know a fix, I'll fix it in a minute.
