### ISSUE TITLE
MSU Settings don't open

### ISSUE THREAD

**Issue by iqnite** [MegaScratchUserscript/Mega-Scratch-Userscript#35]
I go to my profile, click "MSU Settings", wait a bit, but only a blank window appears.

**Comment by cobaltt7** [comment]
It only worked in Scratch 2.0. It has been replaced with Scratch Addons.
________________________________
From: IQNite ***@***.***>
Sent: Friday, April 30, 2021 8:12:17 AM
To: MegaScratchUserscript/Mega-Scratch-Userscript ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MegaScratchUserscript/Mega-Scratch-Userscript] MSU Settings don't open (#35)


I go to my profile, click "MSU Settings", wait a bit, but only a blank window appears.
